version: 1.2
workflows:
  - subclass: WDL
    name: VCFToPlink
    primaryDescriptorPath: /workflows/vcf_to_plink.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BinCpGMethylation
    primaryDescriptorPath: /workflows/bin_cpg_methylation.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BinCpGMethylationCustomBins
    primaryDescriptorPath: /workflows/bin_cpg_methylation_custom_bins.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BuildBedMatrix
    primaryDescriptorPath: /workflows/build_bed_matrix.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: CpGSummaryStats
    primaryDescriptorPath: /workflows/cpg_summary_stats.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

  - subclass: WDL
    name: BuildFilteredCpGMatrix
    primaryDescriptorPath: /workflows/build_filtered_cpg_matrix.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
